name: iso_build_513
on:
  workflow_dispatch:
  schedule:
    - cron:  '45 2 * * *'

jobs:
  prepare_release:
    runs-on: ubuntu-20.04
    steps:
      - 
        name: Prepare Cancel Workflow
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - 
        name: Get current time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
      - 
        name: Prepare Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: Release ${{ steps.time.outputs.time }}
          body: |
            Linux Kernel:
            - linux513
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}

  release:
    runs-on: ubuntu-20.04
    needs: prepare_release    
    strategy:
      matrix:
        ###### EDIT HERE ######
        EDITION: [awesome]
        BRANCH: [stable]
        SCOPE: [minimal]
        #######################
    steps:
      - 
        name: Prepare Cancel Workflow
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - 
        name: Checkout ISO-Profiles
        uses: actions/checkout@v2
        with:
          ###### EDIT HERE ######
          repository: bittin/iso-profiles-1
          #######################
          token: "${{ secrets.GITHUB_TOKEN }}"
          path: 'iso-profiles'
      - 
        name: Get current time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YY.MM'          
      -
        name: Install Build-Dependencies
        run: |
          sudo apt-get update
          sudo apt install gdisk zip systemd-container bmap-tools asciidoc libarchive-tools git build-essential cmake libarchive-dev pkg-config libcurl4-openssl-dev libgpgme-dev libssl-dev fakeroot dh-autoreconf haveged os-prober kwalify dosfstools libisoburn1 squashfs-tools docbook2x

      -
        name: Install Pacman
        run: |          
          sudo git clone https://gitlab.manjaro.org/packages/core/pacman.git
          cd pacman
          sudo wget https://sources.archlinux.org/other/pacman/pacman-5.2.2.tar.gz
          sudo tar -xvf pacman-5.2.2.tar.gz
          cd pacman-5.2.2
          sudo patch -p1 -i ../pacman-sync-first-option.patch
          sudo ./configure --prefix=/usr --sysconfdir=/etc \
            --localstatedir=/var --enable-doc \
            --with-scriptlet-shell=/usr/bin/bash \
            --with-ldconfig=/usr/bin/ldconfig
          sudo make V=1
          sudo make install
          cd ..
          sudo install -m644 pacman.conf /etc/pacman.conf
          sudo install -m644 makepkg.conf /etc/
          sudo mkdir -p /etc/pacman.d
          sudo touch /etc/pacman.d/mirrorlist
          cd ..
      -
        name: Install Keyrings
        run: |          
          sudo git clone https://gitlab.manjaro.org/packages/core/manjaro-keyring.git
          cd manjaro-keyring
          sudo install -dm755 /usr/share/pacman/keyrings/
          sudo install -m0644 manjaro.gpg /usr/share/pacman/keyrings/
          sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
          sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
          cd ..
          
          sudo git clone https://gitlab.archlinux.org/archlinux/archlinux-keyring.git
          cd archlinux-keyring
          sudo install -m0644 archlinux.gpg /usr/share/pacman/keyrings/
          sudo install -m0644 archlinux-trusted /usr/share/pacman/keyrings/
          sudo install -m0644 archlinux-revoked /usr/share/pacman/keyrings/
          cd ..          
                    
          sudo pacman-key --init
          sudo pacman-key --populate archlinux manjaro
      -
        name: Install Arch-Install-Scripts
        run: |          
          pkgver=24
          sudo wget https://github.com/archlinux/arch-install-scripts/archive/refs/tags/v24.tar.gz
          sudo tar -xvf v24.tar.gz
          sudo make -C arch-install-scripts-24
          sudo make -C arch-install-scripts-24 check
          sudo make -C arch-install-scripts-24 PREFIX=/usr install
          
          sudo wget https://gitlab.manjaro.org/applications/pacman-mirrors/-/raw/v4.19x-stable/conf/pacman-mirrors.conf -O /etc/pacman-mirrors.conf
      -
        name: Install Calamares-Tools
        run: |          
          sudo git clone https://gitlab.manjaro.org/applications/calamares-tools.git
          
          install_cal_tools() {
              cd calamares-tools
              sudo install -d /usr/share/calamares/
              sudo cp -rv schemas/ /usr/share/calamares/
              cd ..
          }
          
          install_cal_tools
      -
        name: Install MkInitcpio
        run: |          
          sudo wget https://sources.archlinux.org/other/mkinitcpio/mkinitcpio-30.tar.gz
          sudo tar -xf mkinitcpio-30.tar.gz
          sudo make -C mkinitcpio-30 install
          sudo sed -i -e 's|File|Path|' /usr/share/libalpm/hooks/*hook
      -
        name: Install Manjaro-Tools
        run: |
          sudo git clone https://gitlab.manjaro.org/tools/development-tools/manjaro-tools.git

          install_mjr_tools() {
              cd manjaro-tools
              sudo make SYSCONFDIR=/etc PREFIX=/usr
              sudo make SYSCONFDIR=/etc PREFIX=/usr install_base
              sudo make SYSCONFDIR=/etc PREFIX=/usr install_yaml
              sudo make SYSCONFDIR=/etc PREFIX=/usr install_iso
          }
          
          install_mjr_tools
      -
        name: Build ISO
        env:
          EDITION: ${{ matrix.EDITION }}
          BRANCH: ${{ matrix.BRANCH }}
          SCOPE: ${{ matrix.SCOPE }}
          VERSION: ${{ steps.time.outputs.time }}-development
          ###### EDIT HERE ######
          KERNEL: "linux513"
          CODE_NAME: "Community-Build"
          #######################
        run: |                
          [ "$SCOPE" == "minimal" ] && unset SCOPE
                    
          sudo sed -i -e 's|dist_name=$(get_distname)|dist_name=Manjaro|g' /usr/lib/manjaro-tools/util.sh
          sudo sed -i -e 's|iso_name=$(get_osid)|iso_name=manjaro|g' /usr/lib/manjaro-tools/util.sh
          sudo sed -i -e "s|build_mirror='https://manjaro.moson.eu'|build_mirror='https://mirror.easyname.at/manjaro'|g" /usr/lib/manjaro-tools/util.sh
          sudo sed -i -e "s|dist_release=\$(get_release)|dist_release=$VERSION|g" /usr/lib/manjaro-tools/util.sh
          sudo sed -i -e "s|dist_codename=\$(get_codename)|dist_codename=\"$CODE_NAME\"|g" /usr/lib/manjaro-tools/util.sh
           
          sudo buildiso ${SCOPE:+-f} -p $EDITION -b $BRANCH -k $KERNEL
          
          sudo rm -Rf /var/lib/manjaro-tools/buildiso/*
          
          FILE_PATH=$(find /var/cache/manjaro-tools/iso -type f -name "*.iso" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          zip -j -s 1950m $(basename $FILE_PATH).zip $FILE_PATH
          ls -lasih .
          sha256sum $(basename $FILE_PATH).z* > $(basename $FILE_PATH).sha256

          echo "FILE_PATH=$(basename $FILE_PATH)" >> $GITHUB_ENV
          echo "FILE_SHA256=$(basename $FILE_PATH).sha256" >> $GITHUB_ENV
          
          FILE_PKG=$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          cp -v $FILE_PKG .

          echo "FILE_PKG=$(basename $FILE_PKG)" >> $GITHUB_ENV
      - 
        name: Upload Release
        id: upload_release_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_PATH }}.zip
          asset_name: ${{ env.FILE_PATH }}.zip
          asset_content_type: application/zip
      - 
        name: Check for split-zip
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ env.FILE_PATH }}.z01
          allow_failure: false
      - 
        name: Upload Release (split-zip)
        id: upload_release_z01
        uses: actions/upload-release-asset@v1
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_PATH }}.z01
          asset_name: ${{ env.FILE_PATH }}.z01
          asset_content_type: application/zip
      - 
        name: Upload Checksum file
        id: upload_sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_SHA256 }}
          asset_name: ${{ env.FILE_SHA256 }}
          asset_content_type: text/plain
      - 
        name: Upload Package list
        id: upload_pkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_PKG }}
          asset_name: ${{ env.FILE_PKG }}
          asset_content_type: text/plain     
      - 
        name: Rollback Release
        if: failure()
        uses: author/action-rollback@stable
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
